[[redirects]]
  from = "/api/getAllArea" # 定義路徑
  to = "https://seat.tpml.edu.tw/sm/service/getAllArea" # 要代理的 URL
  status = 200

[[headers]]
  for = "/*"
 [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET"
    Access-Control-Allow-Headers = "application/json, text/plain, */*"

[dev]
  functionsPort = 9000
